[pytest]
markers =
    TC-A1-001a
    TC-A1-001b
    TC-A1-002a
    TC-A1-002b
    TC-A1-003a
    TC-A1-004a
    Performance
    Security
    Negative
    HighPriority
    HappyPath
    Backend
    Poller
    UI